---
 - name: install dnsmasq for tftp
   package:
     name: dnsmasq

 - name: configure dnsmasq for booting
   template:
     src: di-netboot-assistant.j2
     dest: /etc/dnsmasq.d/di-netboot-assistant
   notify: restart_dnsmasq

 - name: di-netboot-assistant
   apt:
     pkg: "{{ item }}"
   with_items:
    - di-netboot-assistant
    - "debian-installer-{{ ansible_distribution_major_version }}-netboot-amd64"
    - "debian-installer-{{ ansible_distribution_major_version }}-netboot-i386"
    - "debian-installer-{{ ansible_distribution_major_version }}-netboot-armel"
    - "debian-installer-{{ ansible_distribution_major_version }}-netboot-armhf"
   notify: update-di

 - name: copy di-netboot-assistant files
   copy:
     src: "{{ item }}"
     dest: "/etc/di-netboot-assistant"
   with_items:
    - di-sources.list
   notify: update-di

 - name: template di-netboot-assistant.conf
   template:
     src: di-netboot-assistant.conf.j2
     dest: /etc/di-netboot-assistant/di-netboot-assistant.conf
   notify: update-di

 - name: remove weekly cronjob
   file:
     dest: "/etc/cron.weekly/di-netboot-assistant"
     state: absent

 - name: create bind mount for tftpdir
   mount:
     src: "/usr/lib/debian-installer/"
     path: "{{ tftp_dir }}/di-netboot-pkg/"
     fstype: auto
     opts: bind
     state: mounted
   notify: update-di
